### ISSUE TITLE
Markdown to CSV

### ISSUE THREAD

**Issue by douglaswaugh** [ArbiterOfBuffoonery/MarkdownFromCSV#1]
Hi,

I really like your plug in and this is more of a feature request than an issue.  Have you thought about extending your plug in so it converts markdown tables back in to CSV?  I actually think it might be easier to edit a CSV table than a markdown table.

Thanks,
Douglas.

**Comment by ArbiterOfBuffoonery** [comment]
Thanks for the feedback! I'm not sure when I will have time to work on this again, but when I do, I'll look into implementing this!

**Comment by ArbiterOfBuffoonery** [comment]
@douglaswaugh I have implemented the ability to convert a markdown table to CSV. Let me know if you see any issues!

**Comment by douglaswaugh** [comment]
Works like a charm!  Thank you very much!
