### ISSUE TITLE
Respect escaped separators

### ISSUE THREAD

**Issue by iliazeus** [ArbiterOfBuffoonery/MarkdownFromCSV#8]
Most software that uses CSV treats this:

```
foo\,bar,baz
```

like this:

```
| foo,bar | baz |
```

I would love for this extension to also respect those escaped separators.

**Comment by ArbiterOfBuffoonery** [comment]
I have been thinking about trying to implement this. Currently the way to have a comma in a column is to enclose the values in quotes. E.g.

```
"foo,bar",baz
```
Result:
```
| "foo,bar" | baz |
```

Would that work instead? It will be a little tricky to implement escaping the comma with `\`. If using quotes doesn't work, I'll continue thinking about the best/cleanest way to implement this.
